name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      working-directory: .
      run: go build -v ./...

    - name: Test
      working-directory: .
      run: go test -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create a new builder
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.8.2
        driver-opts: |
          image=moby/buildkit:v0.10.6
          network=host
        buildkitd-flags: --debug --addr tcp://0.0.0.0:4711

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t thedrwalrus/makemkv:latest --push --cache-from type=local,dest=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache .
