name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      working-directory: .
      run: go build -v ./...

    - name: Test
      working-directory: .
      run: go test -v ./...

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish Docker image
      run: |
        docker build --platform linux/amd64,linux/arm64 -t thedrwalrus/makemkv:latest .
        docker push thedrwalrus/makemkv:latest
